//! Postmortem / after-action export — a one-shot markdown summary of the current
//! IN-SESSION incident, pasteable into a real postmortem doc. PURE formatter; the
//! GUI assembles the inputs + writes the file (the sanctioned one-shot export, no
//! cross-run persistence, no daemon).
//!
//! It composes the things already built upstream — the change timeline (#9), the
//! attention queue, the posture score, and this session's Game Day drills — and
//! does ZERO derivation, only rendering. The timeline section shares the SAME
//! `timeline::row_decisions` the on-screen Annals uses, so the doc and the screen
//! can never disagree about the fault line. Honest about scope: a recent-window /
//! this-session snapshot, not a full audit log. Credential-shaped `key=value`
//! pairs + URL basic-auth in event text are masked before the file leaves the
//! process (defense-in-depth; other secrets may still appear — the footer says so).

use k8s_openapi::jiff::Timestamp;

use super::attention::{Concern, next_action};
use super::posture::{PostureReport, PostureTier};
use super::timeline::{Timeline, row_decisions};
use crate::events::ClusterId;

/// How many open concerns the report lists before "+N more".
const CONCERN_CAP: usize = 25;
/// How many timeline rows (matches the Annals cluster cap).
const TIMELINE_CAP: usize = super::timeline::CLUSTER_CAP;
/// How many posture factors (already points-desc) to surface.
const FACTOR_CAP: usize = 3;

/// Core-friendly mirror of the GUI's `net::ChaosRecord` (core has no GUI/net
/// dep). The GUI maps `chaos_history()` → `Vec<ChaosDrill>` at the boundary.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ChaosDrill {
    pub experiment: String,
    pub target: String,
    pub summary: String,
}

/// Everything the report renders — all built upstream; the formatter only renders.
pub struct PostmortemInput<'a> {
    pub context: &'a str,
    pub platform: &'a str,
    pub version: &'a str,
    pub nodes: usize,
    pub pods: usize,
    pub workloads: usize,
    pub posture: &'a PostureReport,
    pub concerns: &'a [Concern],
    pub timeline: &'a Timeline,
    pub drills: &'a [ChaosDrill],
    /// Tag concerns `[H]`/`[W]` only when a warm world exists.
    pub paired: bool,
    /// `Some(label)` when a namespace filter is active — the concerns, workloads
    /// and timeline are scoped to it (the node/pod census stays cluster-wide), so
    /// the doc says so. `None` = whole realm.
    pub scope: Option<String>,
}

/// THE pure formatter. `now` is injected (clockless core) for the generated-at
/// line + the timeline age strings.
pub fn postmortem_markdown(input: &PostmortemInput, now: Timestamp) -> String {
    let mut s = String::new();
    let stamp = iso(now);

    // --- header / glance ---------------------------------------------------
    s.push_str(&format!(
        "# After-action — {} ({})\n",
        oneline(input.context),
        oneline(input.platform)
    ));
    s.push_str("*Chronicle of the realm — an in-session snapshot.*\n\n");
    s.push_str(&format!(
        "_Generated by Kubernation v{} at {stamp}. In-session snapshot — see Scope._\n\n",
        input.version
    ));
    s.push_str(&format!(
        "**Census:** {} nodes · {} pods · {} workloads\n",
        input.nodes, input.pods, input.workloads
    ));
    s.push_str(&format!("**Posture:** {}\n", posture_line(input.posture)));
    if let Some(scope) = &input.scope {
        s.push_str(&format!(
            "**Scope:** {} — concerns, workloads and the timeline are filtered to this; the node/pod census is cluster-wide.\n",
            oneline(scope)
        ));
    }

    // --- open concerns -----------------------------------------------------
    let mut concerns: Vec<&Concern> = input.concerns.iter().collect();
    concerns.sort_by(|a, b| b.severity.cmp(&a.severity).then(a.key.cmp(&b.key)));
    s.push_str(&format!("\n## Open concerns ({})\n", concerns.len()));
    if concerns.is_empty() {
        s.push_str("_No open concerns._\n");
    } else {
        for c in concerns.iter().take(CONCERN_CAP) {
            let tag = if input.paired {
                match c.cluster {
                    ClusterId::Hot => "  [H]",
                    ClusterId::Warm => "  [W]",
                }
            } else {
                ""
            };
            s.push_str(&format!(
                "- **{} {}** — {}{}\n",
                c.severity.glyph(),
                oneline(&c.title),
                redact(&oneline(&c.detail)),
                tag
            ));
            if let Some(hint) = next_action(c) {
                s.push_str(&format!("  - next: {}\n", oneline(&hint)));
            }
        }
        if concerns.len() > CONCERN_CAP {
            s.push_str(&format!("- _+{} more_\n", concerns.len() - CONCERN_CAP));
        }
    }

    // --- what changed (the timeline) ---------------------------------------
    let tl = input.timeline;
    if !tl.entries.is_empty() {
        s.push_str("\n## What changed\n");
        let decisions = row_decisions(tl, TIMELINE_CAP);
        for (e, d) in tl.entries.iter().take(TIMELINE_CAP).zip(decisions.iter()) {
            if d.fault_line_above {
                s.push_str("- ── trouble begins here ──\n");
            }
            let age = crate::util::format_age_opt_at(now, e.when.as_ref());
            let mut detail = if e.detail.is_empty() {
                oneline(&e.title)
            } else {
                format!("{} — {}", oneline(&e.title), redact(&oneline(&e.detail)))
            };
            if e.count > 1 {
                detail.push_str(&format!("  ×{}", e.count));
            }
            if e.operator {
                detail.push_str("  (you)");
            }
            if d.suspect {
                detail.push_str("  (before the failure)");
            }
            s.push_str(&format!("- `{age}` {} {detail}\n", e.severity.glyph()));
        }
        if tl.entries.len() > TIMELINE_CAP {
            s.push_str(&format!(
                "- _+{} earlier_\n",
                tl.entries.len() - TIMELINE_CAP
            ));
        }
    }

    // --- Game Day drills (this session) ------------------------------------
    if !input.drills.is_empty() {
        s.push_str("\n## Game Day drills (this session)\n");
        for d in input.drills {
            s.push_str(&format!(
                "- {} · {} — {}\n",
                oneline(&d.experiment),
                oneline(&d.target),
                oneline(&d.summary)
            ));
        }
    }

    // --- honesty footer ----------------------------------------------------
    s.push_str("\n---\n");
    s.push_str(&footer(input.posture, tl.window_min, input.version, &stamp));
    s.push('\n');
    s
}

fn posture_line(p: &PostureReport) -> String {
    match p.score {
        None => "UNSCANNED — security scans have no resolved workloads".to_string(),
        Some(score) => {
            let mut line = format!(
                "{} (score {score}/100) — fortifications {} · walls {}",
                tier_word(p.tier),
                p.fortifications.score,
                p.walls.score
            );
            // The top factors dragging it down (already points-desc).
            let top: Vec<String> = p
                .factors
                .iter()
                .take(FACTOR_CAP)
                .map(|f| format!("−{} {}", f.points, oneline(&f.label)))
                .collect();
            if !top.is_empty() {
                line.push_str(&format!("  ({})", top.join("; ")));
            }
            line
        }
    }
}

fn tier_word(t: PostureTier) -> &'static str {
    t.label()
}

fn footer(p: &PostureReport, window_min: i64, version: &str, stamp: &str) -> String {
    let sys = if p.system_critical + p.system_warning > 0 {
        format!(
            " System-namespace findings ({} critical, {} warning) are reported separately and never deducted from the operator posture.",
            p.system_critical, p.system_warning
        )
    } else {
        String::new()
    };
    format!(
        "*Generated by Kubernation v{version} at {stamp}. This is an **in-session snapshot**, \
         not a full audit log: the change feed covers only the last ~{window_min} min of events \
         (plus Deployment rollout history — StatefulSet/DaemonSet revisions live in unwatched \
         ControllerRevisions — and this session's operator actions); Game Day drills and operator \
         actions are **this session only**; there is **no cross-run history**. Security posture is \
         a curated PSS/OWASP subset, not CIS/full-PSS compliance.{sys} Credential-shaped \
         `key=value` / `key: value` pairs, `Bearer` tokens and URL basic-auth in event text are \
         masked best-effort — other secret shapes may remain, so review before sharing.*"
    )
}

/// Filesystem-safe filename: `postmortem-{sanitized-context}-{YYYYMMDD-HHMMSS}.md`.
pub fn postmortem_filename(context: &str, now: Timestamp) -> String {
    format!(
        "postmortem-{}-{}.md",
        sanitize_context(context),
        now.strftime("%Y%m%d-%H%M%S")
    )
}

/// Map a kube context to a path-safe token: non-`[A-Za-z0-9._-]` → `-`, runs
/// collapsed, trimmed. (Contexts can be EKS ARNs full of `:` and `/`.)
pub fn sanitize_context(context: &str) -> String {
    let mut out = String::with_capacity(context.len());
    let mut last_dash = false;
    for c in context.chars() {
        if c.is_ascii_alphanumeric() || c == '.' || c == '_' || c == '-' {
            out.push(c);
            last_dash = false;
        } else if !last_dash {
            out.push('-');
            last_dash = true;
        }
    }
    let trimmed = out.trim_matches('-').to_string();
    if trimmed.is_empty() {
        "cluster".to_string()
    } else {
        trimmed
    }
}

/// ISO-8601 second-precision UTC stamp for the doc body.
fn iso(now: Timestamp) -> String {
    now.strftime("%Y-%m-%dT%H:%M:%SZ").to_string()
}

/// Flatten newlines/tabs (the only true markdown-structure break) and neutralize
/// backticks (a stray one would open a code-span that mis-styles the rest of a
/// line) so an arbitrary event message can't garble the rendered doc.
fn oneline(s: &str) -> String {
    s.replace(['\n', '\r', '\t'], " ")
        .replace('`', "'")
        .trim()
        .to_string()
}

/// Credential key words. A token key matches when it equals one of these or ends
/// with `_<word>` / `-<word>` (a delimiter boundary) — so `db_password` /
/// `api-key` match but a prose word like `mysecret` does NOT (no false positive).
const CRED_KEYS: &[&str] = &[
    "password",
    "passwd",
    "pwd",
    "token",
    "secret",
    "apikey",
    "api_key",
    "api-key",
    "accesskey",
    "access_key",
    "secret_key",
    "client_secret",
    "authorization",
    "bearer",
    "credential",
    "credentials",
];

fn is_cred_key(key: &str) -> bool {
    let k = key.to_ascii_lowercase();
    CRED_KEYS
        .iter()
        .any(|c| k == *c || k.ends_with(&format!("_{c}")) || k.ends_with(&format!("-{c}")))
}

/// Conservative best-effort masking of credential-shaped substrings in free text
/// (the file persists to disk): `key=value` and `key: value` for known credential
/// keys, the `Bearer <token>` / `Authorization:` header shape, and URL basic-auth
/// (`scheme://user:pass@host`, authority only). Fires on explicit patterns — low
/// false-positive; not a guarantee (the footer says so).
///
/// `pub(crate)` because the Oracle's context bundle reuses the SAME free-text
/// scrubber before any LLM egress (one redactor, one set of behaviours, one set
/// of tests — the postmortem export and the Oracle cannot drift).
pub(crate) fn redact(s: &str) -> String {
    // Process PER LINE so newlines/structure survive, splitting each line on ANY
    // whitespace (spaces AND tabs) — a credential must be found regardless of the
    // column separator. This is correct on raw MULTI-LINE input (the Oracle feeds
    // whole log bodies through here, not just `oneline()`-flattened text).
    s.split_inclusive('\n').map(redact_line).collect()
}

/// Redact one line (which may carry its trailing `\n`/`\r`, preserved verbatim).
fn redact_line(line: &str) -> String {
    let (body, nl) = match line.strip_suffix('\n') {
        Some(b) => (b, "\n"),
        None => (line, ""),
    };
    let (body, cr) = match body.strip_suffix('\r') {
        Some(b) => (b, "\r"),
        None => (body, ""),
    };
    let mut out: Vec<String> = Vec::new();
    let mut mask_next = false; // set after a credential "lead" token
    for tok in body.split_whitespace() {
        if mask_next {
            if is_cred_lead(tok) {
                // e.g. "Bearer" between "Authorization:" and the value — keep it,
                // the actual value is still ahead.
                out.push(tok.to_string());
            } else {
                out.push("••••".to_string());
                mask_next = false;
            }
            continue;
        }
        if is_cred_lead(tok) {
            out.push(tok.to_string());
            mask_next = true;
            continue;
        }
        out.push(redact_token(tok));
    }
    format!("{}{cr}{nl}", out.join(" "))
}

/// A standalone credential "lead" whose VALUE is the next token: the bare auth
/// scheme `Bearer`, or a `key:` (colon-terminated) credential key. (The `key=`
/// form is handled inline by `redact_token`.)
fn is_cred_lead(tok: &str) -> bool {
    if tok.eq_ignore_ascii_case("bearer") {
        return true;
    }
    tok.strip_suffix(':').is_some_and(is_cred_key)
}

fn redact_token(tok: &str) -> String {
    // URL basic-auth — only within the AUTHORITY (before the first /?#), so a
    // later `@`/`:` in a path or query (e.g. `?owner=foo@bar.com`) is untouched
    // and the path/query is preserved.
    if let Some(p) = tok.find("://") {
        let rest = &tok[p + 3..];
        let auth_end = rest.find(['/', '?', '#']).unwrap_or(rest.len());
        let auth = &rest[..auth_end];
        if let (Some(at), Some(colon)) = (auth.find('@'), auth.find(':'))
            && colon < at
        {
            return format!(
                "{}://{}:••••{}{}",
                &tok[..p],
                &auth[..colon],
                &auth[at..],
                &rest[auth_end..]
            );
        }
    }
    // key=value for a credential key.
    if let Some(i) = tok.find('=')
        && i + 1 < tok.len()
    {
        let key =
            tok[..i].trim_matches(|c: char| !c.is_ascii_alphanumeric() && c != '_' && c != '-');
        if is_cred_key(key) {
            return format!("{}=••••", &tok[..i]);
        }
    }
    // key:value WITHIN one token — the JSON (`"password":"x"`) / logfmt
    // (`password:x`) shape that no whitespace separates. (The whitespace-
    // separated `key: value` form is handled by `is_cred_lead` in the line loop.)
    if let Some(i) = tok.find(':')
        && i + 1 < tok.len()
    {
        let key =
            tok[..i].trim_matches(|c: char| !c.is_ascii_alphanumeric() && c != '_' && c != '-');
        if is_cred_key(key) {
            return format!("{}:••••", &tok[..i]);
        }
    }
    tok.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::attention::Severity;
    use crate::state::attention::Target;
    use crate::state::posture::{AxisScore, PostureFactor};
    use crate::state::timeline::{ChangeKind, TimelineEntry};
    use k8s_openapi::apimachinery::pkg::apis::meta::v1::Time;
    use k8s_openapi::jiff::SignedDuration;

    fn now() -> Timestamp {
        "2026-06-19T12:00:00Z".parse().unwrap()
    }
    fn ago(s: i64) -> Option<Time> {
        Some(Time(now() - SignedDuration::from_secs(s)))
    }

    fn concern(sev: Severity, title: &str, detail: &str, key: &str) -> Concern {
        Concern {
            severity: sev,
            title: title.into(),
            detail: detail.into(),
            target: Target::WorkloadList,
            probe: None,
            key: key.into(),
            cluster: ClusterId::Hot,
        }
    }

    fn entry(
        kind: ChangeKind,
        sev: Severity,
        when: Option<Time>,
        title: &str,
        detail: &str,
    ) -> TimelineEntry {
        TimelineEntry {
            when,
            kind,
            severity: sev,
            subject: ("demo".into(), title.into(), "Pod".into()),
            title: title.into(),
            detail: detail.into(),
            revision: None,
            count: 1,
            operator: false,
            key: title.into(),
        }
    }

    fn tl(entries: Vec<TimelineEntry>, first_trouble: Option<Time>) -> Timeline {
        Timeline {
            entries,
            first_trouble,
            truncated: false,
            deployment_only_note: false,
            window_min: 15,
        }
    }

    fn posture(score: Option<i32>, tier: PostureTier) -> PostureReport {
        PostureReport {
            score,
            tier,
            scanned: score.is_some(),
            fortifications: AxisScore {
                score: 78,
                ..Default::default()
            },
            walls: AxisScore {
                score: 86,
                ..Default::default()
            },
            workloads_total: 9,
            system_critical: 2,
            system_warning: 0,
            factors: vec![PostureFactor {
                axis: crate::state::posture::Axis::Fortifications,
                kind: crate::state::posture::FactorKind::Warning,
                points: 30,
                label: "5 PSS-restricted gaps".into(),
                detail: "demo/x".into(),
                capped: false,
            }],
        }
    }

    fn input<'a>(
        posture: &'a PostureReport,
        concerns: &'a [Concern],
        timeline: &'a Timeline,
        drills: &'a [ChaosDrill],
        paired: bool,
    ) -> PostmortemInput<'a> {
        PostmortemInput {
            context: "kind-kubernation",
            platform: "kind",
            version: "0.48.0",
            nodes: 4,
            pods: 23,
            workloads: 9,
            posture,
            concerns,
            timeline,
            drills,
            paired,
            scope: None,
        }
    }

    #[test]
    fn scope_line_only_when_filtered() {
        let p = posture(Some(70), PostureTier::Defended);
        let t = tl(vec![], None);
        let whole = postmortem_markdown(&input(&p, &[], &t, &[], false), now());
        assert!(
            !whole.contains("**Scope:**"),
            "no scope line for the whole realm"
        );
        let mut scoped = input(&p, &[], &t, &[], false);
        scoped.scope = Some("kubernation-demo".into());
        let md = postmortem_markdown(&scoped, now());
        assert!(md.contains("**Scope:** kubernation-demo"));
        assert!(md.contains("census is cluster-wide"));
    }

    #[test]
    fn section_order_and_headers() {
        let p = posture(Some(64), PostureTier::Exposed);
        let cs = [concern(
            Severity::Critical,
            "crashy",
            "crash-looping",
            "w:crashy",
        )];
        let t = tl(
            vec![entry(
                ChangeKind::Failure,
                Severity::Critical,
                ago(60),
                "crashy",
                "BackOff",
            )],
            ago(60),
        );
        let drills = [ChaosDrill {
            experiment: "KillOne".into(),
            target: "demo/web".into(),
            summary: "stayed up".into(),
        }];
        let md = postmortem_markdown(&input(&p, &cs, &t, &drills, false), now());
        let h = md.find("# After-action").unwrap();
        let oc = md.find("## Open concerns").unwrap();
        let wc = md.find("## What changed").unwrap();
        let gd = md.find("## Game Day drills").unwrap();
        let ft = md.find("not a full audit log").unwrap();
        assert!(h < oc && oc < wc && wc < gd && gd < ft, "sections in order");
        assert!(md.contains("Generated by Kubernation v0.48.0"));
        assert!(md.contains("4 nodes · 23 pods · 9 workloads"));
    }

    #[test]
    fn empty_realm_is_clean() {
        let p = posture(None, PostureTier::Unscanned);
        let t = tl(vec![], None);
        let md = postmortem_markdown(&input(&p, &[], &t, &[], false), now());
        assert!(md.contains("UNSCANNED"));
        assert!(
            !md.contains("0/100") && !md.contains("/100"),
            "no fake score"
        );
        assert!(md.contains("_No open concerns._"));
        assert!(!md.contains("## What changed"));
        assert!(!md.contains("## Game Day"));
        assert!(md.contains("no cross-run history"));
    }

    #[test]
    fn concerns_sorted_tagged_and_capped() {
        let p = posture(Some(70), PostureTier::Defended);
        let warn = {
            let mut c = concern(Severity::Warning, "stuck", "pvc pending", "p:stuck");
            c.cluster = ClusterId::Warm;
            c
        };
        let crit = concern(Severity::Critical, "crashy", "crash-looping", "w:crashy");
        let cs = [warn, crit];
        let t = tl(vec![], None);
        let md = postmortem_markdown(&input(&p, &cs, &t, &[], true), now());
        // Critical sorts before Warning.
        assert!(md.find("crashy").unwrap() < md.find("stuck").unwrap());
        // Paired ⇒ cluster tags.
        assert!(md.contains("[W]"));
        // next_action hint for the workload concern.
        assert!(md.contains("next:"));
    }

    #[test]
    fn timeline_fault_line_and_suspect_parity() {
        let p = posture(Some(70), PostureTier::Defended);
        let t = tl(
            vec![
                entry(
                    ChangeKind::Failure,
                    Severity::Critical,
                    ago(60),
                    "crashy",
                    "BackOff",
                ),
                entry(
                    ChangeKind::Deploy,
                    Severity::Info,
                    ago(180),
                    "web",
                    "rev 7->8",
                ),
            ],
            ago(60),
        );
        let md = postmortem_markdown(&input(&p, &[], &t, &[], false), now());
        assert!(md.contains("trouble begins here"));
        assert!(
            md.contains("(before the failure)"),
            "the recent deploy is a suspect"
        );
        // Parity: the doc's fault/suspect come from the SAME row_decisions the
        // Annals uses — assert the decision matches.
        let d = row_decisions(&t, TIMELINE_CAP);
        assert!(d[1].fault_line_above && d[1].suspect);
    }

    #[test]
    fn redact_masks_credentials_not_plain_text() {
        assert_eq!(redact("password=hunter2 ok"), "password=•••• ok");
        assert_eq!(redact("token=abc.def"), "token=••••");
        assert_eq!(redact("db_password=x"), "db_password=••••");
        assert_eq!(redact("api-key=x"), "api-key=••••");
        // key: value (colon) + the Bearer / Authorization header shapes.
        assert_eq!(redact("password: hunter2"), "password: ••••");
        assert_eq!(redact("token: abc rotated"), "token: •••• rotated");
        assert_eq!(redact("Bearer eyJhbGci"), "Bearer ••••");
        assert_eq!(
            redact("Authorization: Bearer eyJhbGci done"),
            "Authorization: Bearer •••• done"
        );
        // URL basic-auth, authority only — the port is kept.
        assert_eq!(
            redact("dsn=postgres://user:secretpw@db:5432/x"),
            "dsn=postgres://user:••••@db:5432/x"
        );

        // No false positives / no data loss on plain operator text.
        assert_eq!(
            redact("BackOff: back-off restarting failed container"),
            "BackOff: back-off restarting failed container"
        );
        assert_eq!(
            redact("Scaled up replica set web-7 to 5"),
            "Scaled up replica set web-7 to 5"
        );
        // Prose that merely mentions a credential word is untouched.
        assert_eq!(
            redact("token expired, rotate it"),
            "token expired, rotate it"
        );
        // #4: a key that only ends with a cred substring (no `_`/`-` boundary).
        assert_eq!(redact("mysecret=plainvalue"), "mysecret=plainvalue");
        // #1: a URL with an `@` in the path/query keeps the whole path intact.
        assert_eq!(
            redact("url=postgres://db:5432/x?owner=foo@bar.com"),
            "url=postgres://db:5432/x?owner=foo@bar.com"
        );
    }

    #[test]
    fn filename_stamps_and_sanitizes() {
        let f = postmortem_filename("arn:aws:eks:us-east-1:123:cluster/prod", now());
        assert!(!f.contains('/') && !f.contains(':'), "no path separators");
        assert!(f.starts_with("postmortem-arn-aws-eks-us-east-1-123-cluster-prod-"));
        assert!(f.ends_with(".md"));
        assert!(f.contains("20260619-120000"));
        assert_eq!(sanitize_context("kind-kubernation"), "kind-kubernation");
        assert_eq!(sanitize_context(":::"), "cluster");
    }

    #[test]
    fn footer_echoes_window_and_system_findings() {
        let p = posture(Some(64), PostureTier::Exposed); // system_critical = 2
        let t = tl(vec![], None);
        let md = postmortem_markdown(&input(&p, &[], &t, &[], false), now());
        assert!(
            md.contains("last ~15 min"),
            "window_min echoed, not hardcoded"
        );
        assert!(
            md.contains("2 critical, 0 warning"),
            "system findings noted in footer"
        );
        assert!(md.contains("not CIS/full-PSS"));
    }
}
